name: med_freq_2
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.5 <3.0.0'



dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.1.0
  step_progress_indicator: ^1.0.0
  mask_text_input_formatter: ^2.3.0
  clipboard: ^0.1.3
  url_launcher: ^6.1.3
  responsive_framework: ^0.2.0
  search_app_bar_page: ^2.1.3
  timeline_tile: ^2.0.0
  folding_cell: ^1.0.2
  colored_print: ^0.0.2
  bot_toast: ^4.0.2
  cupertino_icons: ^1.0.2
  #audioplayers: ^0.20.1
  intl: ^0.17.0
  flutter_image_compress: ^1.1.0
  flutter_staggered_grid_view: ^0.4.1
  path_provider: ^2.0.11
  crop_your_image: ^0.7.2
  #android_intent: ^2.0.2 - depreceated - https://pub.dev/packages/android_intent_plus
  image_picker: ^0.8.5+3
  permission_handler: ^9.2.0
  google_ml_kit: ^0.11.0
  shared_preferences: ^2.0.15


  ### fire packages ###

  firebase_auth: ^3.5.0
  google_sign_in: ^5.4.0
  cloud_firestore: ^3.4.0
  firebase_core: ^1.20.0

  ### hasura packages ###

  hasura_connect: ^4.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.9.3
  lint: ^1.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/heart-pulses_2_white.png"
flutter_native_splash:
  color: "#e0e0e0"
  image: assets/heart-pulses_2.png
  fullscreen: true